name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Foundry Version
        run: |
          forge --version

      - name: Format Code
        run: |
          forge fmt --check
        id: fmt

      - name: Compile Contracts
        run: |
          forge build --sizes
        id: build

      - name: Run Unit Tests
        run: |
          forge test -vvv
        id: test
